name: "[Tests] Test Go"
description: "Run go test suite"

inputs:
    github_token:
      description: "A valid github token"
      required: true
    cache:
      description: "cache go.mod"
      default: "true"


runs:
  using: composite
  steps:
    # checkout self
    - name: "Checkout"
      id: checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
        fetch-tags: true
    # setup the go version and pull from cache etc
    - name: "Setup go"
      id: setup_go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        cache: ${{ inputs.cache }}
        go-version-file: './go.mod'
    # run tests
    - name: "Run tests"
      id: run_tests
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        go mod tidy
        go test -count=1 -cover -covermode=atomic ./...




