name: "Go: Tests"
description: "Run tests for the go code base"

runs:
  using: "composite"
  steps:
    # checkout self
    - name: "Checkout"
      id: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    # setup the go version and pull from cache etc
    - name: "Setup go"
      id: setup_go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #v5.3.0
      with:
        cache: false
        go-version-file: './go.mod'
    # run the tests and output the results as a json file
    - name: "Run tests"
      id: run_tests
      shell: bash
      env:
        LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
        LOG_TO: "stdout"
      run: |
        go test -cover -covermode=atomic -v ./...
