# Use go release to make local build easier
# - goreleaser build --clean --single-target --skip=validate
version: 2

dist: ./builds/go

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # data seeding binary - will create fake data for local demo
  - id: seeder_cmd
    binary: seeder_cmd
    main: ./seeder/
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  # -- servers
  - id: api_server
    binary: api
    main: ./servers/api/
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: front_server
    binary: front
    main: ./servers/front/
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  # -- reports
  - id: github_standards_cmd
    binary: github_standards_cmd
    main: ./commands/github_standards/
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
