# Use go release to make local build easier
# - goreleaser build --clean --single-target --skip=validate
version: 2

dist: ./builds/go

before:
  hooks:
    - go mod tidy
    - go generate ./...


builds:
  - id: demo_data_cmd
    binary: demo_data_cmd
    main: ./demo/
    no_unique_dist_dir: true
    hooks:
      # generate sample csv files and database
      post: make dbs
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: github_standards_cmd
    binary: github_standards_cmd
    main: ./commands/github_standards/
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
