# Use go release to make local build easier
# - goreleaser build --clean --single-target --skip=validate
version: 2

dist: ./builds/binaries

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - sh -c "cd ./datastore/github_standards/ && sqlc generate"
    - sh -c "mkdir -p ./builds/api/ ./builds/front ./builds/commands"
    - sh -c "cp ./datastore/github_standards/schema.sql ./builds/api/github_standards.sql"

builds:
  # -- data seeder - can create fake data
  - id: seeder_cmd
    binary: seeder_cmd
    main: ./seeder/
    no_unique_dist_dir: true
    hooks:
      post: sh -c "cp ./builds/binaries/seeder_cmd ./builds/api/seeder_cmd"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  # -- servers
  - id: api_server
    binary: api_server
    main: ./servers/api/
    no_unique_dist_dir: true
    hooks:
      post: sh -c "cp ./builds/binaries/api_server ./builds/api/api_server"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: front_server
    binary: front_server
    main: ./servers/front/
    no_unique_dist_dir: true
    hooks:
      post: sh -c "cp ./builds/binaries/front_server ./builds/front/front_server"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  # -- reports
  - id: github_standards_cmd
    binary: github_standards_cmd
    main: ./commands/github_standards/
    no_unique_dist_dir: true
    hooks:
      post: sh -c "cp ./builds/binaries/github_standards_cmd ./builds/commands/github_standards_cmd"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

