services:
  api:
    # image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-reports/api:latest
    image: opg-reports/api:latest
    container_name: opg-reports-api
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      # AWS_REGION: ${AWS_REGION}
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      DATABASE_PATH: "api.db"
      SERVERS_API_ADDR: ":8081"
    ports:
      - "8081:8081"

  # front:
  #   # image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-reports/front:latest
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: docker/front/Dockerfile
  #   environment:
  #     API_ADDR: api:8081
  #     FRONT_ADDR: :8080
  #   ports:
  #     - "8080:8080"
