services:
  api:
    platform: linux/arm64
    build:
      target: development
    ports:
      - "8081:8081"
    volumes:
      - ./report:/app/report:rw,delegated
      - ./go.mod:/app/go.mod:rw,delegated
      - ./go.sum:/app/go.sum:rw,delegated

  # front:
  #   platform: linux/arm64
  #   build:
  #     target: development
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./info:/app/info
  #     - ./internal:/app/internal
  #     - ./models:/app/models
  #     - ./seed:/app/seed
  #     - ./servers:/app/servers
  #     - ./Makefile:/src
  #     - ./go.mod:/app/go.mod
  #     - ./go.sum:/app/go.sum
