services:
  api:
    # image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-reports/api:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_ADDR: ":8081"
    ports:
      - "8081:8081"

  front:
    # image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-reports/front:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    environment:
      API_ADDR: api:8081
      FRONT_ADDR: :8080
    ports:
      - "8080:8080"
