db:
  driver: "sqlite3"
  path: "./api.db"
  params: "?_journal=WAL&_busy_timeout=5000&_vacuum=incremental&_synchronous=NORMAL&_cache_size=1000000000"

github:
  token: ""

log:
  level: "info"
  type: "json"
