name: "Terraform: Plan & Apply"
description: "Plan and apply the terraform. Presumes workflow is already authenticated."

inputs:
  version:
    description: "Terraform version number to use"
    required: true
  directory:
    description: "Working directory to run the terraform from."
    required: true
  workspace:
    description: "Terraform workspace to utilise"
    required: true
  lint:
    description: "When 'true', run tf linting. Default: true"
    default: "true"
  apply:
    description: "When 'true' then the terraform will be applied. Default: false"
    required: true
    default: "false"


runs:
  using: "composite"
  steps:
    # setup the terraform version
    - name: "Setup terraform [version: ${{ inputs.version }}]"
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ inputs.version }}
    # run linting against the terraform (if requested)
    - name: "Lint"
      id: lint
      shell: bash
      working-directory: ${{ inputs.directory }}
      if: ${{ inputs.lint == 'true' }}
      run: |
        terraform fmt -check -recursive
    # run the terraform init
    - name: "Init"
      id: init
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        terraform init -input=false -lock-timeout=300s
    # run the terraform plan and output that to a file for use in apply
    - name: "Plan"
      id: plan
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}
        PLAN_FILE: ${{ inputs.workspace }}.plan
      run: |
        echo -e "workspace:"
        terraform workspace show
        terraform plan -lock-timeout=300s -input=false -out=${{ env.PLAN_FILE }} -parallelism=30
    # run the terraform applt (if true) from the plan file
    - name: "Apply [apply: ${{ inputs.apply == 'true' }}]"
      id: apply
      shell: bash
      working-directory: ${{ inputs.directory }}
      if: ${{ inputs.apply == 'true' }}
      env:
        TF_WORKSPACE: ${{ inputs.workspace }}
        PLAN_FILE: ${{ inputs.workspace }}.plan
      run: |
        terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30
