version: "3.6"

services:
  # api:
  #   platform: linux/arm64
  #   build:
  #     target: dev
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./builds:/app/builds
  #     - ./datastore:/app/datastore
  #     - ./seeder:/app/seeder
  #     - ./servers:/app/servers
  #     - ./shared:/app/shared
  #     - ./Makefile:/app/Makefile
  #     - ./go.mod:/app/go.mod
  #     - ./go.sum:/app/go.sum

  front:
    platform: linux/arm64
    build:
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./builds:/app/builds
      - ./datastore:/app/datastore
      - ./seeder:/app/seeder
      - ./servers:/app/servers
      - ./shared:/app/shared
      - ./Makefile:/app/Makefile
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
