#!/usr/bin/env bash
set -eo pipefail

# dirty function to remove any relative paths
d() { cd "${1}"; pwd; }

readonly SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# this is the root directory of the project repository
readonly ROOT_DIR=$(d "${SCRIPT_DIR}/../../")

# load in modules
source ${SCRIPT_DIR}/defaults.sh
source ${SCRIPT_DIR}/logs.sh
source ${SCRIPT_DIR}/dry-run.sh

source ${SCRIPT_DIR}/files.sh
source ${SCRIPT_DIR}/workflows.sh
source ${SCRIPT_DIR}/makefile.sh



main() {
    local bucket_dev="${BUCKET_NAME_DEV}"

    # -- actions that dont require input
    # delete unused github actions
    delete_files "${GITHUB_WORKFLOW_DIR}" "${GITHUB_REPORT_PATTERN}" "${GITHUB_REPORT_KEEP}"
    # remove the terraform directory
    delete_directory "${TERRAFORM_DIR}"
    # remove terraform and related steps from workflows
    gh_workflow_remove_marked "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}"
    gh_workflow_remove_marked "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}"

    # -- actions that need user input
    # DEVELOPMENT
    # get the bucket name
    read -p "Provide the name of your *DEVELOPMENT* bucket used for data storage: [${bucket_dev}] " bucket_dev
    bucket_dev="${bucket_dev:-$BUCKET_NAME_DEV}"
    echo "value: [${bucket_dev}]"
    log ${INFO} ""

    # update workflow
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_REPORT_KEEP}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    # - only for dev
    makefile_replace_bucket "${ROOT_DIR}" "${MAKEFILE}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
}

main
