#!/usr/bin/env bash
set -eo pipefail

# dirty function to remove any relative paths
d() { cd "${1}"; pwd; }

readonly SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# this is the root directory of the project repository
readonly ROOT_DIR=$(d "${SCRIPT_DIR}/../../")

# load in modules
source ${SCRIPT_DIR}/defaults.sh
source ${SCRIPT_DIR}/logs.sh
source ${SCRIPT_DIR}/dry-run.sh

source ${SCRIPT_DIR}/files.sh
source ${SCRIPT_DIR}/workflows.sh
source ${SCRIPT_DIR}/makefile.sh



main() {
    local bucket_dev="${BUCKET_NAME_DEV}"
    local bucket_download_dev="${BUCKET_DOWNLOAD_ROLE_DEV}"
    local bucket_upload_dev="${BUCKET_UPLOAD_ROLE_DEV}"
    local ecr_push_dev="${ECR_PUSH_ROLE_DEV}"
    local profile_dev="${MAKEFILE_AWS_PROFILE}"
    # -- actions that dont require input
    # delete unused github actions
    delete_files "${GITHUB_WORKFLOW_DIR}" "${GITHUB_REPORT_PATTERN}" "${GITHUB_REPORT_KEEP}"
    # remove the terraform directory
    delete_directory "${TERRAFORM_DIR}"
    # remove terraform and related steps from workflows
    gh_workflow_remove_marked "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}"
    gh_workflow_remove_marked "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}"

    # -- actions that need user input
    # DEVELOPMENT
    ### BUCKETS
    read -p "Provide the name of your *DEVELOPMENT* bucket used for data storage: [${bucket_dev}] " bucket_dev
    bucket_dev="${bucket_dev:-$BUCKET_NAME_DEV}"
    echo "value: [${bucket_dev}]"
    log ${INFO} ""

    # update workflow
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_REPORT_KEEP}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    # - only for dev
    makefile_replace_bucket "${ROOT_DIR}" "${MAKEFILE}" "${BUCKET_NAME_DEV}" "${bucket_dev}"

    ### AWS PROFILE
    # - only for dev
    read -p "Provide your *DEVELOPMENT* aws profile for local s3 download [${profile_dev}] " profile_dev
    profile_dev="${profile_dev:-$MAKEFILE_AWS_PROFILE}"
    echo "value: [${profile_dev}]"
    log ${INFO} ""

    makefile_replace_aws_profile "${ROOT_DIR}" "${MAKEFILE}" "${MAKEFILE_AWS_PROFILE}" "${profile_dev}"

    ### WORKFLOW S3 DOWNLOAD ROLE
    read -p "Provide the *DEVELOPMENT* role ARN to use for downloading from the s3 bucket [${bucket_download_dev}] " bucket_download_dev
    bucket_download_dev="${bucket_download_dev:-$BUCKET_DOWNLOAD_ROLE_DEV}"
    echo "value: [${bucket_download_dev}]"
    log ${INFO} ""

    gh_workflow_replace_bucket_download_role "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}" "${BUCKET_DOWNLOAD_ROLE_DEV}" "${bucket_download_dev}"

    ## WORKFLOW S3 UPLOAD ROLE
    read -p "Provide the *DEVELOPMENT* OIDC role ARN to use for uploading to the s3 bucket [${bucket_upload_dev}] " bucket_upload_dev
    bucket_upload_dev="${bucket_upload_dev:-$BUCKET_UPLOAD_ROLE_DEV}"
    echo "value: [${bucket_upload_dev}]"
    log ${INFO} ""

    gh_workflow_replace_bucket_upload_role "${GITHUB_WORKFLOW_DIR}" "${GITHUB_REPORT_KEEP}" "${BUCKET_UPLOAD_ROLE_DEV}" "${bucket_upload_dev}"

    ### ECR REGISTRY ID
    ### ECR REGISTRY docker compse - 311462405659.dkr.ecr.eu-west-1.amazonaws.com/opg-reports
    #   ecr_registry_id: "311462405659"
    #   ecr_repository_api: "opg-reports/api"
    #   ecr_repository_front: "opg-reports/front"

    ### WORKFLOW ECR PUSH ROLE
    read -p "Provide the *DEVELOPMENT* OIDC role ARN to use for pushing to ecr [${ecr_push_dev}] " ecr_push_dev
    ecr_push_dev="${ecr_push_dev:-$ECR_PUSH_ROLE_DEV}"
    echo "value: [${ecr_push_dev}]"
    log ${INFO} ""

    gh_workflow_replace_ecr_push_role "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_PR}" "${ECR_PUSH_ROLE_DEV}" "${ecr_push_dev}"

    ### front/config.json setup


    # PRODUCTION - as we currently use dev everywhere, just repeat
    gh_workflow_replace_bucket "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}" "${BUCKET_NAME_DEV}" "${bucket_dev}"
    gh_workflow_replace_bucket_download_role "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}" "${BUCKET_DOWNLOAD_ROLE_DEV}" "${bucket_download_dev}"
    gh_workflow_replace_ecr_push_role "${GITHUB_WORKFLOW_DIR}" "${GITHUB_WORKFLOW_LIVE}" "${ECR_PUSH_ROLE_DEV}" "${ecr_push_dev}"

}

main
