// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package awsu

type AwsUptime struct {
	ID      int     `json:"id"`
	Ts      string  `json:"ts"`
	Unit    string  `json:"unit"`
	Average float64 `json:"average"`
	Date    string  `json:"date"`
}

type AwsUptimeTracker struct {
	ID      int    `json:"id"`
	RunDate string `json:"run_date"`
}
