name: "Report"
description: "Run a report"

inputs:
  name:
    description: "Display name of the report."
    required: true
  cmd:
    description: "Name of the binary to run"
    required: true
  arguments:
    description: "String containing all arguments for the command"
    required: true
    default: ""


outputs:
  build_folder:
    description: "Path to the folder containing the built versions of the code base"
    value: ${{steps.build_go.outputs.build_folder}}
  data_folder:
    description: "Path to the folder containing the built versions of the code base"
    value: ${{ steps.setup_data_dir.outputs.DATA_FOLDER }}


runs:
  using: "composite"
  steps:
    - name: "Checkout"
      id: checkout
      uses: actions/checkout@v4
    - name: "Build"
      id: "build_go"
      uses: ./.github/actions/go_build
      with:
        target: "reports"
    - name: "Setup data directory"
      id: setup_data_dir
      working-directory: ${{ steps.build_go.outputs.build_folder }}
      shell: bash
      env:
        data_folder: ${{ steps.build_go.outputs.build_folder }}/data
      run: |
        rm -Rf ${{ env.data_folder }}
        mkdir -p ${{ env.data_folder }}
        echo "DATA_FOLDER=${{ env.data_folder }}" >> $GITHUB_OUTPUT
    - name: "Run report"
      id: run_report
      shell: bash
      working-directory: ${{ steps.build_go.outputs.build_folder }}
      env:
        cmd_args: ${{ inputs.arguments }}
      run: |
        ./${{ inputs.cmd }} ${{ env.cmd_args }}
        ls -lah ./data/*
        ls -lah ${{ steps.setup_data_dir.outputs.DATA_FOLDER }}
    ###############
    #   SUMMARY
    ###############
    - name: "Summary"
      id: summary
      shell: bash
      run:  |
        echo "### Report Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
        echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
        echo "| name | ${{ inputs.name }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| cmd | ${{ inputs.cmd }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| arguments | ${{ inputs.arguments }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| directory | ${{ steps.build_go.outputs.build_folder }} |"  >> $GITHUB_STEP_SUMMARY
        echo "| data folder | ${{ steps.setup_data_dir.outputs.DATA_FOLDER }} |"  >> $GITHUB_STEP_SUMMARY
