name: "Get opg-metadata AWS account matrix"
description: "Use go to fetch the account data and output for matrix"

inputs:
  token:
    description: "toke to use to fetch the data from opg-metadata"
    required: true
  dir:
    description: "Directory where everyhting is built in from make."
    default: "./builds"

outputs:
  matrix:
    description: "Matrix formatted string that can be imported as json to use as job stratergy."
    value: ${{ steps.data.outputs.matrix }}


runs:
  using: composite
  steps:
    # checkout
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    # setup go
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        cache: false
        go-version-file: './go.mod'
    # run make
    - name: "make"
      shell: bash
      run: |
          make build-cmds
          chmod -Rf 0777 ${{ env.BUILD_DIR }}
          ls -lth ${{ env.BUILD_DIR }}
    # run the command
    - name: "run accounts command"
      shell: bash
      env:
        cmd: ${{ inputs.dir }}/accounts/accounts
        filename: ${{ inputs.dir }}/accounts/aws.accounts.json
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        ${{ env.cmd }} --file="${{ env.filename}}"
        ls -lRth ${{ inputs.dir }}
    - name: "capture json"
      id: data
      shell: bash
      env:
        filename: ${{ inputs.dir }}/accounts/aws.accounts.json
        debug: ${{ runner.debug == '1' && 'debug' || '' }}
      run: |
        data=$(cat ${{ env.filename }})
        matrix="{ "include": ${data} }"
        echo "matrix<<EOF" >> $GITHUB_OUTPUT
        echo "${matrix}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        if [[ "${{ env.debug }}" == "debug" ]]; then
          echo "${matrix}"
        fi

