name: "Docker: Build, Scan and Push"
description: "Build docker images"

inputs:
  branch_name:
    description: "Git branch name"
    required: true

  tag:
    description: "Semver tag value"
    required: true

  dockerfile:
    description: "Path to Dockerfile"
    required: true

  docker_build_args:
    description: "Build arguments for docker"
    default: ""

  buildx_version:
    description: "Buildx version"
    default: "v0.15.1"

  buildx_platforms:
    description: "List of platforms to generate images for"
    default: "linux/amd64"

  ecr_repository:
    description: "Name of ECR repository"
    required: true

  ecr_registry_id:
    description: "AWS registry ID"
    default: "311462405659"

  checkout_repo:
    description: "Force a checkout of the repository"
    default: "false"

  path_to_live:
    description: "When set to true, pushes images following production conventions."
    default: "false"
# outputs:


runs:
  using: "composite"
  steps:
    # checkout self
    - name: "Force checkout repository"
      if: ${{ inputs.checkout_repo == 'true' }}
      id: checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0
        fetch-tags: true
    # QEMU for multi platforms
    - name: Set up QEMU
      id: setup_qemu
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
    # Setup docker buildx
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      id: docker_buildx_setup
      with:
        version: ${{ inputs.buildx_version }}
        platforms: ${{ inputs.buildx_platforms }}
    # Login to ecr registry
    - name: "ECR login"
      id: ecr_login
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        mask-password: true
        registries: ${{ inputs.ecr_registry_id }}
    # Build image
    - name: "Build image [image: ${{ inputs.ecr_repository }} ]"
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      env:
        SOURCE_DATE_EPOCH: 0
        BUILD_TAG: ${{ inputs.tag }}
        EXTRA_BUILD_ARGS: ${{ inputs.docker_build_args }}
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.buildx_platforms }}
        push: false
        load: true
        cache-from: type=registry,ref=${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:cache-${{ inputs.branch_name }}
        tags: |
          ${{ inputs.ecr_repository }}:${{ inputs.tag }}
        build-args: |
          TAG=${{ env.BUILD_TAG }}
          ${{ env.EXTRA_BUILD_ARGS }}

    # Push the image
    # for a PR
    - name: "Push image to ECR [PR]"
      if: ${{ inputs.path_to_live != 'true' }}
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      env:
        SOURCE_DATE_EPOCH: 0
        BUILD_TAG: ${{ inputs.tag }}
        EXTRA_BUILD_ARGS: ${{ inputs.docker_build_args }}
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        builder: ${{ steps.docker_buildx_setup.outputs.name }}
        push: true
        platforms:  ${{ inputs.buildx_platforms }}
        cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:cache-${{ inputs.branch_name }}
        tags: |
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.tag }}
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:development-${{ inputs.tag }}
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:development-latest
        build-args: |
          TAG=${{ env.BUILD_TAG }}
          ${{ env.EXTRA_BUILD_ARGS }}

    - name: "Summary [tag: ${{ inputs.tag }}]"
      shell: bash
      if: ${{ inputs.path_to_live != 'true' }}
      run: |
        echo "tags:"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.tag }}"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:development-${{ inputs.tag }}"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:development-latest"  >> $GITHUB_STEP_SUMMARY

    # For live
    - name: "Push image to ECR [Path to live]"
      if: ${{ inputs.path_to_live == 'true' }}
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      env:
        SOURCE_DATE_EPOCH: 0
        BUILD_TAG: ${{ inputs.tag }}
        EXTRA_BUILD_ARGS: ${{ inputs.docker_build_args }}
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        builder: ${{ steps.docker_buildx_setup.outputs.name }}
        push: true
        platforms: ${{ inputs.buildx_platforms }}
        cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:cache-${{ inputs.branch_name }}
        tags: |
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.tag }}
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:main-${{ inputs.tag }}
          ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:latest
        build-args: |
          TAG=${{ env.BUILD_TAG }}
          ${{ env.EXTRA_BUILD_ARGS }}

    - name: "Summary [Path to live]"
      shell: bash
      if: ${{ inputs.path_to_live == 'true' }}
      run: |
        echo "tags:"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.tag }}"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:main-${{ inputs.tag }}"  >> $GITHUB_STEP_SUMMARY
        echo "- ${{ steps.ecr_login.outputs.registry }}/${{ inputs.ecr_repository }}:latest"  >> $GITHUB_STEP_SUMMARY
