// Package ghs
// NOT generated by sqlc
package ghs

import (
	"fmt"

	"github.com/ministryofjustice/opg-reports/shared/convert"
)

func (g *GithubStandard) UID() string {
	return g.FullName
}

func (g *GithubStandard) Info() map[string]string {
	return map[string]string{
		"archived":                   fmt.Sprintf("%t", convert.IntToBool(g.IsArchived)),
		"created_at":                 fmt.Sprintf("%s", g.CreatedAt),
		"branch_name":                g.DefaultBranch,
		"has_delete_branch_on_merge": fmt.Sprintf("%t", convert.IntToBool(g.HasDeleteBranchOnMerge)),
		"has_pages":                  fmt.Sprintf("%t", convert.IntToBool(g.HasPages)),
		"has_downloads":              fmt.Sprintf("%t", convert.IntToBool(g.HasDownloads)),
		"has_discussions":            fmt.Sprintf("%t", convert.IntToBool(g.HasDiscussions)),
		"has_wiki":                   fmt.Sprintf("%t", convert.IntToBool(g.HasWiki)),
		"forks":                      fmt.Sprintf("%d", g.CountOfForks),
		"webhooks":                   fmt.Sprintf("%d", g.CountOfWebHooks),
		"open_pull_requests":         fmt.Sprintf("%d", g.CountOfPullRequests),
		"clone_traffic":              fmt.Sprintf("%d", g.CountOfClones),
		"is_private":                 fmt.Sprintf("%t", convert.IntToBool(g.IsPrivate)),
		"last_commit_date":           fmt.Sprintf("%s", g.LastCommitDate),
	}
}

func (g *GithubStandard) Baseline() map[string]bool {
	return map[string]bool{
		"has_default_branch_of_main":         convert.IntToBool(g.HasDefaultBranchOfMain),
		"has_license":                        convert.IntToBool(g.HasLicense),
		"has_issues":                         convert.IntToBool(g.HasIssues),
		"has_description":                    convert.IntToBool(g.HasDescription),
		"has_rules_enforced_for_admins":      convert.IntToBool(g.HasRulesEnforcedForAdmins),
		"has_pull_request_approval_required": convert.IntToBool(g.HasPullRequestApprovalRequired),
	}
}

func (g *GithubStandard) Extended() map[string]bool {
	return map[string]bool{
		"has_code_owner_approval_required": convert.IntToBool(g.HasCodeownerApprovalRequired),
		"has_readme":                       convert.IntToBool(g.HasReadme),
		"has_code_of_conduct":              convert.IntToBool(g.HasCodeOfConduct),
		"has_contributing_guide":           convert.IntToBool(g.HasContributingGuide),
	}
}

func (g *GithubStandard) UpdateCompliance() (baseline int, extended int) {
	baselineChecks := map[string]bool{
		"has_default_branch_of_main":         (g.HasDefaultBranchOfMain == 1),
		"has_license":                        (g.HasLicense == 1),
		"has_issues":                         (g.HasIssues == 1),
		"has_description":                    (g.HasDescription == 1),
		"has_rules_enforced_for_admins":      (g.HasRulesEnforcedForAdmins == 1),
		"has_pull_request_approval_required": (g.HasPullRequestApprovalRequired == 1),
	}
	extendedChecks := map[string]bool{
		"has_code_owner_approval_required": (g.HasCodeownerApprovalRequired == 1),
		"has_readme":                       (g.HasReadme == 1),
		"has_code_of_conduct":              (g.HasCodeOfConduct == 1),
		"has_contributing_guide":           (g.HasContributingGuide == 1),
	}

	baseline = 1
	extended = 1

	for _, is := range baselineChecks {
		if !is {
			baseline = 0
		}
	}
	for _, is := range extendedChecks {
		if !is {
			extended = 0
		}
	}
	g.CompliantBaseline = baseline
	g.CompliantExtended = extended

	return
}

func (g *GithubStandard) ToCSV() (line string) {

	line = fmt.Sprintf(`%d,"%s",%d,%d,%d,%d,%d,%d,"%s","%s","%s",%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,"%s","%s","%s","%s","%s"`,
		g.ID,
		g.Ts,
		g.CompliantBaseline,
		g.CompliantExtended,
		g.CountOfClones,
		g.CountOfForks,
		g.CountOfPullRequests,
		g.CountOfWebHooks,
		g.CreatedAt,
		g.DefaultBranch,
		g.FullName,
		g.HasCodeOfConduct,
		g.HasCodeownerApprovalRequired,
		g.HasContributingGuide,
		g.HasDefaultBranchOfMain,
		g.HasDefaultBranchProtection,
		g.HasDeleteBranchOnMerge,
		g.HasDescription,
		g.HasDiscussions,
		g.HasDownloads,
		g.HasIssues,
		g.HasLicense,
		g.HasPages,
		g.HasPullRequestApprovalRequired,
		g.HasReadme,
		g.HasRulesEnforcedForAdmins,
		g.HasVulnerabilityAlerts,
		g.HasWiki,
		g.IsArchived,
		g.IsPrivate,
		g.License,
		g.LastCommitDate,
		g.Name,
		g.Owner,
		g.Teams,
	) + "\n"
	return
}

func (g *GithubStandard) CSVHead() (line string) {
	line = fmt.Sprintf(`"%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s","%s"`,
		"id",
		"ts",
		"compliant_baseline",
		"compliant_extended",
		"count_of_clones",
		"count_of_forks",
		"count_of_pull_requests",
		"count_of_web_hooks",
		"created_at",
		"default_branch",
		"full_name",
		"has_code_of_conduct",
		"has_codeowner_approval_required",
		"has_contributing_guide",
		"has_default_branch_of_main",
		"has_default_branch_protection",
		"has_delete_branch_on_merge",
		"has_description",
		"has_discussions",
		"has_downloads",
		"has_issues",
		"has_license",
		"has_pages",
		"has_pull_request_approval_required",
		"has_readme",
		"has_rules_enforced_for_admins",
		"has_vulnerability_alerts",
		"has_wiki",
		"is_archived",
		"is_private",
		"license",
		"last_commit_date",
		"name",
		"owner",
		"teams",
	) + "\n"
	return
}
