// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package ghs

type GithubStandard struct {
	Uuid                           string `json:"uuid"`
	Ts                             string `json:"ts"`
	DefaultBranch                  string `json:"default_branch"`
	FullName                       string `json:"full_name"`
	Name                           string `json:"name"`
	Owner                          string `json:"owner"`
	License                        string `json:"license"`
	LastCommitDate                 string `json:"last_commit_date"`
	CreatedAt                      string `json:"created_at"`
	CountOfClones                  int    `json:"count_of_clones"`
	CountOfForks                   int    `json:"count_of_forks"`
	CountOfPullRequests            int    `json:"count_of_pull_requests"`
	CountOfWebHooks                int    `json:"count_of_web_hooks"`
	HasCodeOfConduct               int    `json:"has_code_of_conduct"`
	HasCodeownerApprovalRequired   int    `json:"has_codeowner_approval_required"`
	HasContributingGuide           int    `json:"has_contributing_guide"`
	HasDefaultBranchOfMain         int    `json:"has_default_branch_of_main"`
	HasDefaultBranchProtection     int    `json:"has_default_branch_protection"`
	HasDeleteBranchOnMerge         int    `json:"has_delete_branch_on_merge"`
	HasDescription                 int    `json:"has_description"`
	HasDiscussions                 int    `json:"has_discussions"`
	HasDownloads                   int    `json:"has_downloads"`
	HasIssues                      int    `json:"has_issues"`
	HasLicense                     int    `json:"has_license"`
	HasPages                       int    `json:"has_pages"`
	HasPullRequestApprovalRequired int    `json:"has_pull_request_approval_required"`
	HasReadme                      int    `json:"has_readme"`
	HasRulesEnforcedForAdmins      int    `json:"has_rules_enforced_for_admins"`
	HasVulnerabilityAlerts         int    `json:"has_vulnerability_alerts"`
	HasWiki                        int    `json:"has_wiki"`
	IsArchived                     int    `json:"is_archived"`
	IsPrivate                      int    `json:"is_private"`
}
