name: "[Tests] Test Go code"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  # run the full go test suite for this app
  test_go:
    name: "Go test suite"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
      - name: "Running tests"
        env:
          LOG_LEVEL: ${{ runner.debug == '1' && 'debug' || 'error' }}
          LOG_TO: "stdout"
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          echo "" > report.xml
          go test -v -json ./... > test-results.json 2>&1 || true
          go-junit-report -parser gojson -in test-results.json -out report.xml || true
      # - name: "debug"
      #   run: |
      #     ls -larth ./test-results.json
      #     ls -larth ./report.xml
      #     go test -v -json ./...
      #     cat ./report.xml
      # generate test report for this run
      - name: Test Report
        id: report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          fail-on-error: false
          path: ./report.xml
          reporter: java-junit
      - name: Output results link
        run:  |
          echo "**[Test results](${{steps.report.outputs.url_html}})**" >> $GITHUB_STEP_SUMMARY
      - name: Test failure
        if: ${{ steps.report.outputs.conclusion != 'success' }}
        run: |
          echo "Test failed, please see summary: ${{steps.report.outputs.url_html}}"
          exit 1
