name: "[PR] Workflow"

on:
  pull_request:
    branches: [main]

jobs:
  # run all tests
  tests:
    name: "[Tests]"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    name: "Build"
    needs: [tests]
    steps:
      - name: "Checkout self"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: "Semver tag"
      #   id: semver_tag
      #   uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v3.0.6
      #   with:
      #     prerelease: ${{ github.ref != 'refs/heads/main' }}
      #     releases_enabled: false # disable the release as we want to attach artifacts

  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [tests, build]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
