name: "[Reports] AWS Monthly Costs"

on:
  pull_request:
    branches:
      - main

  schedule:
    # 8am on the 15th of every month
    - cron: '0 8 15 * *'
  workflow_dispatch:
    inputs:
      month:
        description: "YYYY-MM formatted month to get cost data for."
        type: string
        default: "-"

permissions:
  id-token: write
  contents: read

jobs:
  report:
    name: "Run AWS monthly costs"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### Service accounts:
          # Digideps
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps development"
            account_id: 248804316466
            account_environment: "development"
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps pre-production"
            account_id: 454262938596
            account_environment: "pre-production"
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps production"
            account_id: 515688267891
            account_environment: "production"
          # Make
          - account_unit: "Make"
            account_label: "Make"
            account_name: "Make development"
            account_id: "050256574573"
            account_environment: "development"
          - account_unit: "Make"
            account_label: "Make"
            account_name: "Make pre-production"
            account_id: 987830934591
            account_environment: "pre-production"
          - account_unit: "Make"
            account_label: "Make"
            account_name: "Make production"
            account_id: 980242665824
            account_environment: "production"
          # Modernise
          - account_unit: "Modernise"
            account_label: "Modernise"
            account_name: "Modernise development"
            account_id: 653761790766
            account_environment: "development"
          - account_unit: "Modernise"
            account_label: "Modernise"
            account_name: "Modernise pre-production"
            account_id: 792093328875
            account_environment: "pre-production"
          - account_unit: "Modernise"
            account_label: "Modernise"
            account_name: "Modernise production"
            account_id: 313879017102
            account_environment: "production"
          # Refunds
          - account_unit: "Legacy"
            account_label: "Refunds"
            account_name: "Refunds production"
            account_id: 805626386523
            account_environment: "production"
          # Serve
          - account_unit: "Serve"
            account_label: "Serve"
            account_name: "Serve development"
            account_id: 705467933182
            account_environment: "development"
          - account_unit: "Serve"
            account_label: "Serve"
            account_name: "Serve pre-production"
            account_id: 540070264006
            account_environment: "pre-production"
          - account_unit: "Serve"
            account_label: "Serve"
            account_name: "Serve production"
            account_id: 933639921819
            account_environment: "production"
          # Sirius
          - account_unit: "Sirius"
            account_label: "Sirius"
            account_name: "Sirius development"
            account_id: 288342028542
            account_environment: "development"
          - account_unit: "Sirius"
            account_label: "Sirius"
            account_name: "Sirius pre-production"
            account_id: 492687888235
            account_environment: "pre-production"
          - account_unit: "Sirius"
            account_label: "Sirius"
            account_name: "Sirius production"
            account_id: 649098267436
            account_environment: "production"
          - account_unit: "Sirius"
            account_label: "Sirius"
            account_name: "Sirius backup"
            account_id: 132068124730
            account_environment: "backup"
          # Sirius LPA Store
          - account_unit: "Sirius"
            account_label: "LPA Store"
            account_name: "LPA Store development via MP"
            account_id: 493907465011
            account_environment: "development"
          - account_unit: "Sirius"
            account_label: "LPA Store"
            account_name: "LPA Store pre-production"
            account_id: 936779158973
            account_environment: "pre-production"
          - account_unit: "Sirius"
            account_label: "LPA Store"
            account_name: "LPA Store production"
            account_id: 764856231715
            account_environment: "production"
          # Use
          - account_unit: "Use"
            account_label: "Use"
            account_name: "Use development"
            account_id: 367815980639
            account_environment: "development"
          - account_unit: "Use"
            account_label: "Use"
            account_name: "Use pre-production"
            account_id: 888228022356
            account_environment: "pre-production"
          - account_unit: "Use"
            account_label: "Use"
            account_name: "Use production"
            account_id: 690083044361
            account_environment: "production"
          # ### Shared ORG accounts
          - account_unit: "ORG"
            account_label: "ORG Backup"
            account_name: "Backup"
            account_id: 238302996107
            account_environment: "production"
          - account_unit: "ORG"
            account_label: "ORG Identity"
            account_name: "Identity"
            account_id: 631181914621
            account_environment: "production"
          - account_unit: "ORG"
            account_label: "ORG Sandbox"
            account_name: "Sandbox"
            account_id: 995199299616
            account_environment: "development"
          # - account_unit: "ORG"
          #   account_label: "ORG Management"
          #   account_name: "Management"
          #   account_id: 311462405659
          #   account_environment: "production"
          - account_unit: "ORG"
            account_label: "ORG Shared"
            account_name: "Shared development"
            account_id: 679638075911
            account_environment: "development"
          - account_unit: "ORG"
            account_label: "ORG Shared"
            account_name: "Shared production"
            account_id: 997462338508
            account_environment: "production"
          ### Legacy
          # old shared
          - account_unit: "Legacy"
            account_label: "Legacy Shared"
            account_name: "Legacy Shared"
            account_id: 357766484745
            account_environment: "production"
          # old refunds prod
          - account_unit: "Legacy"
            account_label: "Old Refunds"
            account_name: "Legacy old refunds production"
            account_id: 574983609246
            account_environment: "production"
          # old make prod
          - account_unit: "Legacy"
            account_label: "Make"
            account_name: "Legacy make production"
            account_id: 550790013665
            account_environment: "production"

    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      # configure the aws role for costs
      - name: "Configure AWS credentials for running the report"
        id: configure_aws_creds_report
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: "arn:aws:iam::${{ matrix.account_id }}:role/gh-actions-cost-metrics"
          role-session-name: opg-reports-get-costs
      # run report
      - name: "Run report"
        id: run
        env:
          month: ${{ inputs.month != '' && inputs.month || '-' }}
          unit: ${{ matrix.account_unit }}
          label: ${{ matrix.account_label }}
          name: ${{ matrix.account_name }}
          id: ${{ matrix.account_id }}
          environment: ${{ matrix.account_environment }}
        uses: ./.github/actions/report
        with:
          name: "AWS monthly costs"
          cmd: "aws_cost_monthly"
          arguments: '-month "${{ env.month }}"  -account_unit "${{ env.unit }}" -account_label "${{ env.label }}" -account_name "${{ env.name }}" -account_id "${{ env.id }}" -account_environment "${{ env.environment }}" '
      # configure the aws role for s3 upload
      - name: "Configure AWS credentials for S3 upload"
        id: configure_aws_creds_bucket
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: "eu-west-1"
          role-to-assume: "arn:aws:iam::679638075911:role/docs-and-metadata-ci"
          role-session-name: opg-reports-upload-costs-to-s3
      # upload
      - name: "Upload to s3"
        uses: ./.github/actions/s3_upload
        with:
          directory: ${{ steps.run.outputs.data_folder }}
          bucket: "report-data-development"
          bucket_path: "aws/cost/monthly"
