name: "[Reports] Repository Standards"

on:
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - '.github/workflows/report_repository_standards.yml'

  schedule:
    # 9am saturday
    - cron: '0 9 * * 6'

  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:

  report:
    name: "Run repository standards report"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "Run report"
        id: run
        uses: ./.github/actions/report
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
        with:
          name: "Repository standards"
          cmd: "github_standards"
          arguments: '-organisation ministryofjustice -team opg'
      # configure the aws role
      - name: "Configure AWS credentials for S3 upload"
        id: configure_aws_creds_s3_upload
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: "arn:aws:iam::679638075911:role/opg-reports-github-actions-s3"
          role-session-name: opg-reports-upload-github-standards-to-s3
      - name: "Upload to s3"
        id: upload_to_s3
        uses: ./.github/actions/s3_upload
        with:
          directory: ${{ steps.run.outputs.data_folder }}
          bucket: "report-data-development"
          bucket_path: "github/standards"
