name: "[Reports] AWS Monthly Costs"

on:
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - '.github/workflows/report_aws_monthly_costs.yml'

  schedule:
    # 8am on the 15th of every month
    - cron: '0 8 15 * *'
  workflow_dispatch:
    inputs:
      month:
        description: "YYYY-MM formatted month to get cost data for."
        type: string
        default: "-"

permissions:
  id-token: write
  contents: read

jobs:
  load_matrix:
    name: "Load matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.account_matrix.outputs.matrix }}
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "get account matrix"
        id: account_matrix
        uses: "./.github/actions/get_opg_metadata"
        with:
          github_token: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
          prereleases: false


  report:
    name: "Run AWS monthly costs"
    runs-on: ubuntu-latest
    needs: [load_matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load_matrix.outputs.matrix) }}

    steps:
      - name: "Checkout"
        id: checkout
        if: ${{ matrix.type == 'aws' }}
        uses: actions/checkout@v4
      # configure the aws role for costs
      - name: "Configure AWS credentials for running the report"
        id: configure_aws_creds_report
        if: ${{ matrix.type == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: "arn:aws:iam::${{ matrix.account_id }}:role/gh-actions-cost-metrics"
          role-session-name: opg-reports-get-costs
      # run report
      - name: "Run report"
        id: run
        if: ${{ matrix.type == 'aws' }}
        env:
          month: ${{ inputs.month != '' && inputs.month || '-' }}
          unit: ${{ matrix.billing-unit }}
          label: ${{ matrix.label }}
          name: ${{ matrix.name }}
          id: ${{ matrix.id }}
          environment: ${{ matrix.environment }}
        uses: ./.github/actions/report
        with:
          name: "AWS monthly costs"
          cmd: "aws_cost_monthly"
          arguments: '-month "${{ env.month }}"  -account_unit "${{ env.unit }}" -account_label "${{ env.label }}" -account_name "${{ env.name }}" -account_id "${{ env.id }}" -account_environment "${{ env.environment }}" '
      # configure the aws role for s3 upload
      - name: "Configure AWS credentials for S3 upload"
        id: configure_aws_creds_bucket
        if: ${{ matrix.type == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: "arn:aws:iam::679638075911:role/opg-reports-github-actions-s3"
          role-session-name: opg-reports-upload-costs-to-s3
      # upload
      - name: "Upload to s3"
        if: ${{ matrix.type == 'aws' }}
        uses: ./.github/actions/s3_upload
        with:
          directory: ${{ steps.run.outputs.data_folder }}
          bucket: "report-data-development"
          bucket_path: "aws/cost/monthly"
