name: "[Reports] Repository Standards"

on:

  schedule:
    # 9am saturday
    - cron: '0 9 * * 6'
  workflow_dispatch:

jobs:

  report:
    name: "Run repository standards report"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "Run report"
        id: run
        uses: ./.github/actions/report
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
        with:
          name: "Repository standards"
          cmd: "github_standards"
          arguments: '-organisation ministryofjustice -team opg'
      # configure the aws role
      - name: "Configure AWS credentials for S3 upload"
        id: configure_aws_creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: "eu-west-1"
          role-to-assume: "arn:aws:iam::679638075911:role/docs-and-metadata-ci"
          role-session-name: GitHubActionsOpgReportsBucketUpload
      - name: "Upload to s3"
        uses: ./.github/actions/s3_upload
        with:
          directory: ${{ steps.run.outputs.data_folder }}
          bucket: "report-data-development"
          bucket_path: "github/standards"
