name: "[Reports] AWS Costs"

on:
  # run on 3am on the 15th of every month
  schedule:
    - cron: '0 3 15 * *'
  # run when triggered manually
  workflow_dispatch:
    inputs:
      month:
        description: "YYYY-MM-DD formatted month to get cost data for."
        type: string
        default: "-"
  # temp - run on pr so can test this workflow
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write

env:
  PRERELEASE: true

# jobs
jobs:
  setup:
    name: "Set variables"
    runs-on: ubuntu-latest
    outputs:
      # AWS S3 bucket & role info - used to downlo
      s3_bucket_development: "report-data-development"
      s3_role_development: "arn:aws:iam::679638075911:role/opg-reports-github-actions-s3"
      # Account matrix
      account_matrix: ${{ steps.account_matrix.outputs.matrix }}
    steps:
      # Check the code base
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # Get AWS account list
      - name: "Get account matrix"
        id: account_matrix
        uses: ./.github/actions/get-aws-accounts-matrix
        with:
          github_token: ${{ secrets.GH_ORG_ACCESS_TOKEN }}

  # runner
  runner:
    name: "Run Report"
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: "Create dir"
        run: mkdir -p ./releases/
      - name: "Download release"
        uses: ./.github/actions/download-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ env.PRERELEASE }}
      - name: "List build directory"
        run: ls -laRh ./builds/
      # download database
      # run import
      # upload database

  # final step
  end:
    name: 'End'
    runs-on: 'ubuntu-latest'
    needs:
      - runner
    steps:
      - id: end
        name: End
        run: echo "End"
