name: "[Reports] Codebase Stats"
on:
  # pull_request:
  #   branches:
  #     - main

  # run at 03:30 on Sunday, Tuesday, and Thursday.
  schedule:
    - cron: '30 3 * * 0,2,4'

# permissions
permissions:
  contents: write
  id-token: write
  actions: read
  pull-requests: none

jobs:
  # use the importer workflow to run everything
  run:
    name: "Run codebases stats command"
    uses: ./.github/workflows/_importer_github.yml
    secrets: inherit
    with:
      sub_cmd: "codebase-stats"
      upload_to_prod: true
  # an end step for cleaner workflow
  end:
    name: "End"
    runs-on: ubuntu-24.04
    needs:
      - run
    steps:
      - run: |
          echo "done"
