name: "[Reports] Codebases & Codeowners"
on:
  # pull_request:
  #   branches:
  #     - main
  # run at 03:00 daily
  schedule:
    - cron: '0 3 * * *'

# permissions
permissions:
  contents: write
  id-token: write
  actions: read
  pull-requests: none

jobs:
  # run code base import
  run_codebases:
    name: "Run codebases command"
    uses: ./.github/workflows/_importer_github.yml
    secrets: inherit
    with:
      sub_cmd: "codebases"
      upload_to_prod: false
  # run code owner import
  run_codeowners:
    name: "Run codeowners command"
    needs:
      - run_codebases
    uses: ./.github/workflows/_importer_github.yml
    secrets: inherit
    with:
      sub_cmd: "codeowners"
      upload_to_prod: false
  # an end step for cleaner workflow
  end:
    name: "End"
    runs-on: ubuntu-24.04
    needs:
      - run_codebases
      - run_codeowners
    steps:
      - run: |
          echo "done"
