name: "[Reports] AWS Monthly Costs"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_report.yml'
      - '.github/workflows/report_aws_monthly_costs.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_report.yml'
      - '.github/workflows/report_aws_monthly_costs.yml'
  schedule:
    # 8am on the 15th of every month
    - cron: '0 8 15 * *'
  workflow_dispatch:
    inputs:
      month:
        description: "YYYY-MM formatted month to get cost data for."
        type: string
        default: "-"
jobs:
  # run all tests
  tests:
    name: "Tests"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit


  report:
    needs: [tests]
    strategy:
      fail-fast: false
      matrix:
        include:
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps Development"
            account_id: 248804316466
            account_environment: "Development"
            role: billing
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps Pre-Production"
            account_id: 454262938596
            account_environment: "Pre-Production"
            role: billing
          - account_unit: "Digideps"
            account_label: "Digideps"
            account_name: "Digideps Production"
            account_id: 515688267891
            account_environment: "Production"
            role: billing
    uses: './.github/workflows/_report.yml'
    secrets: inherit
    with:
      name: "Aws monthly costs [${{ matrix.account_name }}]"
      arguments: '-account_unit ${{ matrix.account_unit }} -account_label ${{ matrix.account_label }} -account_name ${{ matrix.account_name }} -account_id ${{ matrix.account_id }} -account_environment ${{ matrix.account_environment }} -role ${{ matrix.role}} -month ${{inputs.month}}'
      directory: './cmd/report/aws/cost/monthly/'
      upload: true
      bucket_suffix: 'aws/cost/monthly'
      bucket: ${{ github.ref == 'refs/heads/main' && 'report-data-production' || 'report-data-development' }}
      role: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::997462338508:role/docs-and-metadata-ci' || 'arn:aws:iam::679638075911:role/docs-and-metadata-ci' }}
