name: "[Reports] AWS Costs"

on:
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - '.github/workflows/report_aws_costs.yml'

  schedule:
    # 8am on the 15th of every month
    - cron: '0 8 15 * *'

  workflow_dispatch:
    inputs:
      month:
        description: "YYYY-MM formatted month to get cost data for."
        type: string
        default: "-"

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      aws_s3_bucket: "report-data-development"
      aws_role_s3_upload: "arn:aws:iam::679638075911:role/opg-reports-github-actions-s3"
      github_org: "ministryofjustice"
      github_team: "opg"
    steps:
      - name: "End"
        run: echo "end"

  load_matrix:
    name: "Load matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.account_matrix.outputs.matrix }}
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "get account matrix"
        id: account_matrix
        uses: "./.github/actions/get_opg_metadata"
        with:
          github_token: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
          prereleases: false

  report:
    name: "Run aws costs report"
    runs-on: ubuntu-latest
    needs: [setup, load_matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load_matrix.outputs.matrix) }}

    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "Configure AWS credentials for running the report"
        id: configure_aws_creds_report
        if: ${{ matrix.type == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: "arn:aws:iam::${{ matrix.id }}:role/gh-actions-cost-metrics"
          role-session-name: opg-reports-get-costs
      - name: "Run report"
        id: run
        uses: ./.github/actions/report
        env:
          month: ${{ inputs.month != '' && inputs.month || '-' }}
          unit: ${{ matrix.billing_unit }}
          label: ${{ matrix.label }}
          name: ${{ matrix.name }}
          id: ${{ matrix.id }}
          environment: ${{ matrix.environment != '' && matrix.environment || 'production' }}
        with:
          name: "aws costs"
          cmd: "aws_costs_cmd"
          arguments: '-month "${{ env.month }}"  -unit "${{ env.unit }}" -label "${{ env.label }}" -name "${{ env.name }}" -id "${{ env.id }}" -environment "${{ env.environment }}" '
      # configure the aws role
      - name: "Configure AWS credentials for S3 upload"
        id: configure_aws_creds_s3_upload
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          role-duration-seconds: 900
          role-to-assume: ${{ needs.setup.outputs.aws_role_s3_upload }}
          role-session-name: reports-upload-github-standards-to-s3
      # - name: "Upload to s3"
      #   id: upload_to_s3
      #   uses: ./.github/actions/s3_upload
      #   with:
      #     directory: ${{ steps.run.outputs.data_folder }}
      #     bucket: ${{ needs.setup.outputs.aws_s3_bucket }}
      #     bucket_path: "aws_costs"
