name: "[Workflow] Run Repository Report"

on:
  schedule:
    # 8am every day
    - cron: "0 8 * * *"

permissions:
  actions: read
  pull-requests: read
  contents: none
  id-token: none
  security-events: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  identify_repos:
    name: "Identify Repositories Requiring Attention"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4

      - name: "Install Python"
        uses: actions/setup-python@55aad42e4674b58b2b2fb7d8e7552402d922b4e7
        with:
          python-version: "3.12"

      - name: "Run Requirements Installation"
        id: requirements
        run: pip install -r requirements.txt
        working-directory: ./scripts/neglected_repos

      - name: "Run Script"
        id: run_script
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: python check_for_neglected_repos.py
        working-directory: ./scripts/neglected_repos
