name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: read
  security-events: write
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  # run the go tests
  run_pre_build_tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: "test_go"
        name: "Go"
        uses: ./.github/actions/go-tests
  # build database downloader command
  build_commands:
    name: "Setup"
    needs: ["run_pre_build_tests"]
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: "database_cmd"
        name: "Database command"
        uses: ./.github/actions/build-command
        with:
          name: "db"
          source: "./report/cmd/db/"
          destination: "./builds/bin/"

  # final step
  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [build_commands]
    steps:
      - id: end
        name: End
        run: echo "End"
