name: "[Workflow] Test getting json from remote"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  pull-requests: read
  security-events: write
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  load_matrix:
    name: "Load matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.account_matrix.outputs.matrix}}
    steps:
      - name: "get account matrix"
        id: account_matrix
        uses: "./.github/actions/get_opg_metadata"
        with:
          github_token: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
          prereleases: true

  use_matrix:
    needs: [load_matrix]
    name: "test matrix"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.load_matrix.outputs.matrix) }}
    steps:
      - run: |
          echo "id: ${{ matrix.id }}"
          echo "name: ${{ matrix.name }}"
