name: "[Workflow] Pull Request"

on:
  pull_request:
    branches:
      - main


jobs:
  # setup series of variables either calculated or fixed for this workflow that
  # are used though out the other jobs / steps
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      terraform_workspace: "development"
      terraform_version_account: ${{ steps.terraform_account_version.outputs.version }}
      terraform_version_environment: ${{ steps.terraform_environment_version.outputs.version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Parse terraform account version"
        id: terraform_account_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/account
      - name: "Parse terraform environment version"
        id: terraform_environment_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/environment

  # build & test go
  build_go:
    name: "[Go] Test & Build"
    runs-on: ubuntu-latest
    needs: [setup]
    outputs:
      go_artifact_path: ""
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "Build"
        id: "build_go"
        uses: ./.github/actions/go_build
        with:
          target: "all"
          skip_tests: false

  # Run the terraform for development workspace
  terraform:
    name: "[Terraform] Development"
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v4
      - name: "Account level terraform"
        uses: ./.github/actions/terraform
        with:
          apply: true
          directory: ./terraform/account
          workspace: ${{ needs.setup.outputs.terraform_workspace }}
          version: ${{ needs.setup.outputs.terraform_version_account }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      - name: "Environment level terraform"
        uses: ./.github/actions/terraform
        with:
          apply: true
          directory: ./terraform/account
          workspace: ${{ needs.setup.outputs.terraform_workspace }}
          version: ${{ needs.setup.outputs.terraform_version_environment }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  # helper to output summary of steps
  summary:
    name: "Summary"
    if: always()
    needs: [setup, terraform]
    runs-on: ubuntu-latest
    steps:
      - name: "Terraform"
        run: |
          echo "### Terraform info" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform workspace | ${{ needs.setup.outputs.terraform_workspace }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform account version | ${{ needs.setup.outputs.terraform_version_account }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform environment version | ${{ needs.setup.outputs.terraform_version_environment }} |"  >> $GITHUB_STEP_SUMMARY

  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [terraform, summary]
    steps:
      - id: end
        name: End
        run: echo "End"
