name: "[Workflow] Pull Request"

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      terraform_workspace: "development"
      terraform_version_account: ${{ steps.terraform_account_version.outputs.version }}
      terraform_version_environment: ${{ steps.terraform_environment_version.outputs.version }}
      development_account_id: "679638075911"
      role: "docs-and-metadata-ci"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Parse terraform account version"
        id: terraform_account_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/account
      - name: "Parse terraform environment version"
        id: terraform_environment_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/environment

  # run all tests
  go_tests:
    name: "[Go] Tests"
    uses: './.github/workflows/_tests.yml'
    secrets: inherit

  # run account level terraform
  terraform_development_account:
    if: ${{ github.ref != 'refs/heads/main' }}
    needs: [setup]
    name: "[Terraform] Development Account"
    uses: './.github/workflows/_terraform.yml'
    with:
      apply: true
      directory: ./terraform/account
      workspace: ${{ needs.setup.outputs.terraform_workspace }}
      version: ${{ needs.setup.outputs.terraform_version_account }}
    secrets: inherit

  # run env level terraform
  terraform_development_environment:
    needs: [setup, terraform_development_account]
    name: "[Terraform] Development Environment"
    uses: './.github/workflows/_terraform.yml'
    with:
      apply: true
      directory: ./terraform/environment
      workspace: ${{ needs.setup.outputs.terraform_workspace }}
      version: ${{ needs.setup.outputs.terraform_version_environment }}
    secrets: inherit


  # helper to output summary of steps
  summary:
    name: "Summary"
    if: always()
    needs: [setup, terraform_development_environment]
    runs-on: ubuntu-latest
    steps:
      - name: "Terraform"
        run: |
          echo "### Terraform info" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform workspace | ${{ needs.setup.outputs.terraform_workspace }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform account version | ${{ needs.setup.outputs.terraform_version_account }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform environment version | ${{ needs.setup.outputs.terraform_version_environment }} |"  >> $GITHUB_STEP_SUMMARY


  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [go_tests, terraform_development_environment]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
