name: "[Workflow - Terraform] Path to live"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - './.github/workflows/_terraform.yml'
      - './.github/workflows/workflow_terraform_pr.yml'
      - './.github/workflows/workflow_terraform_path_to_live.yml'

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      terraform_workspace: production
      terraform_version_account: ${{ steps.terraform_account_version.outputs.version }}
      terraform_version_environment: ${{ steps.terraform_environment_version.outputs.version }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Parse terraform account version"
        id: terraform_account_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/account
      - name: "Parse terraform environment version"
        id: terraform_environment_version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v3.0.6
        with:
          terraform_directory: ./terraform/environment

  # run dev level account terraform
  terraform_development_account:
    needs: [setup]
    name: "[Terraform] Development Account"
    uses: './.github/workflows/_terraform.yml'
    with:
      apply: true
      directory: ./terraform/account
      workspace: development
      version: ${{ needs.setup.outputs.terraform_version_account }}
    secrets: inherit

  # run dev level environment terraform
  terraform_development_environment:
    needs: [setup, terraform_development_account]
    name: "[Terraform] Development Environment"
    uses: './.github/workflows/_terraform.yml'
    with:
      apply: true
      directory: ./terraform/environment
      workspace: development
      version: ${{ needs.setup.outputs.terraform_version_environment }}
    secrets: inherit

  # run prod level account
  # terraform_production_account:
  #   needs: [setup, terraform_development_environment ]
  #   name: "[Terraform] Production Account"
  #   uses: './.github/workflows/_terraform.yml'
  #   with:
  #     apply: true
  #     directory: ./terraform/account
  #     workspace: production
  #     version: ${{ needs.setup.outputs.terraform_version_account }}
  #   secrets: inherit


  # # run prod level environment terraform
  # terraform_production_environment:
  #   needs: [setup, terraform_production_account]
  #   name: "[Terraform] Production Environment"
  #   uses: './.github/workflows/_terraform.yml'
  #   with:
  #     apply: true
  #     directory: ./terraform/environment
  #     workspace: production
  #     version: ${{ needs.setup.outputs.terraform_version_environment }}
  #   secrets: inherit


  # helper to output summary of steps
  summary:
    name: "Summary"
    if: always()
    needs: [setup, terraform_development_environment]
    runs-on: ubuntu-latest
    steps:
      - name: "Terraform"
        run: |
          echo "### Terraform info" >> $GITHUB_STEP_SUMMARY
          echo "| Variable | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform workspace | ${{ needs.setup.outputs.terraform_workspace }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform account version | ${{ needs.setup.outputs.terraform_version_account }} |"  >> $GITHUB_STEP_SUMMARY
          echo "| terraform environment version | ${{ needs.setup.outputs.terraform_version_environment }} |"  >> $GITHUB_STEP_SUMMARY


  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [go_tests, terraform_development_environment]
    # needs: [go_tests, terraform_development_environment, terraform_production_environment]
    steps:
      - id: end
        name: End
        run: |
          echo "End"
