name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: read
  security-events: write
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none


jobs:
  # run all the go tests
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      # checkout self
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      # run tests
      - id: "test_go"
        name: "Go"
        uses: ./.github/actions/go-tests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # build all of the commands - jsut to make sure nothing fails
  builds:
    name: "Builds"
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "api"
            src: "./report/cmd/api/"
          - name: "db"
            src: "./report/cmd/db/"
          - name: "front"
            src: "./report/cmd/front/"
          - name: "govuk"
            src: "./report/cmd/govuk/"
          - name: "importer"
            src: "./report/cmd/importer/"
    steps:
      # checkout self
      - name: "Checkout [${{ matrix.name }}]"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: "Build [${{ matrix.name }}] command"
        uses: ./.github/actions/build-command
        with:
          name: ${{ matrix.name }}
          source: ${{ matrix.src }}
          destination: "./builds/bin/"
      - name: "list"
        run: ls -l ./builds/bin/





  # final step
  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [builds]
    steps:
      - id: end
        name: End
        run: echo "End"
