name: "[Workflow] Test getting json from remote"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  pull-requests: read
  security-events: write
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "get release"
        env:
          GH_TOKEN: ${{ secrets.GH_ORG_ACCESS_TOKEN }}
        run: |
          gh release list --repo ministryofjustice/opg-metadata
