name: "[Workflow] TEST GITHUB ACTION"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write


jobs:
  test_uses:
    name: "TEST GitHub Action"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: "branchname"
        id: "branchname"
        uses: ministryofjustice/opg-github-actions/actions/branch-name@v4.2.0-semveraction.4

      - name: "semver - should return last release"
        id: "semver_last_release"
        uses: ministryofjustice/opg-github-actions/actions/semver@v4.2.0-semveraction.4
        with:
          test: true
          create_release: false
          prerelease: false
          default_bump: "none"

      - name: "semver - should return a prerelease string"
        id: "semver_prelease"
        uses: ministryofjustice/opg-github-actions/actions/semver@v4.2.0-semveraction.4
        with:
          test: true
          create_release: false
          prerelease: true
          default_bump: "none"

      # # pull in remote action by just the version number
      # - id: "versioned_remote_action"
      #   name: "Versioned"
      #   uses: ministryofjustice/opg-github-actions/actions/test-env@v4.1.2-semveraction.5
      # # # pull in remote action by the exact sha
      # - id: "pinned_remote_action"
      #   name: "Pinned"
      #   uses: ministryofjustice/opg-github-actions/actions/test-gha@3c942e078d2b3d48dab3ff9e293a435c27115d22


